# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 16:39
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_bug_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='voter',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
