# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20181103_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
