# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20181103_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='voter',
        ),
    ]
