# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_bugcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomment',
            name='bug',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='issues.Bug'),
        ),
    ]
