# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20181104_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugcomment',
            name='published_date',
        ),
    ]
