# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_remove_bugcomment_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='ref',
            field=models.CharField(default=123, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
