# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20181105_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Testing', 'Testing'), ('Closed', 'Closed')], max_length=15),
        ),
    ]
