# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_auto_20181105_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='costperhour',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
            preserve_default=False,
        ),
    ]
