# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_feature_costperhour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='costperhour',
            new_name='cost_per_hour',
        ),
    ]
