# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_auto_20181105_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='ref',
            field=models.CharField(default='Feat-12345', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
