# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_feature_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
    ]
