# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_auto_20181105_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Under Development', 'Under Development'), ('Testing', 'Testing'), ('Closed', 'Closed')], default='Pending Payment', max_length=15),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Under Development', 'Under Development'), ('Testing', 'Testing'), ('Closed', 'Closed')], default='Open', max_length=15),
        ),
    ]
