# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0028_bugcomment_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Under Development', 'Under Development'), ('Testing', 'Testing'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
