# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0029_auto_20181117_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='dev_hours_req',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Under Review', 'Under Review'), ('Target not Reached', 'Target not Reached'), ('Under Development', 'Under Development'), ('Testing', 'Testing'), ('Deployed', 'Deployed')], default='Pending Payment', max_length=20),
        ),
    ]
