# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0031_bugvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
