# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181108_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Donor',
        ),
    ]
