# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
